seed: 1
total_num_scenes: 36
num_processes: 1
num_eval_episodes: 1000
cuda: true
sim_gpu_id: 1
log_interval: 10
save_interval: 1
dump_location: "./outputs/experiments/"
experiment_id: "20250509_(wo_rl)_(matchpoint80_dis50)"
save_periodic: 50000
visualize: 1 # output video
environment: "habitat"
env_frame_width: 480
env_frame_height: 640
frame_width: 120
frame_height: 160
max_episode_length: 1000
task_config: "tasks/instance_imagenav.yaml"
split: "val"
camera_height: 0.88
hfov: 79
turn_angle: 30
min_depth: 0.00
max_depth: 30.0
success_dist: 1.0
floor_thr: 50
min_d: 1.5
max_d: 100.0
version: "v3"
lr: 2.5e-5
global_hidden_size: 256
eps: 1.0e-5
alpha: 0.99
gamma: 0.99
use_gae: false
tau: 0.95
entropy_coef: 0.001
value_loss_coef: 0.5
max_grad_norm: 0.5
num_global_steps: 20
ppo_epoch: 4
num_mini_batch: 1
clip_param: 0.2
use_recurrent_global: 0
num_local_steps: 40
reward_coeff: 0.1
intrinsic_rew_coeff: 0.02
sem_pred_prob_thr: 0.50
global_downscaling: 3
vision_range: 100
du_scale: 1
cat_pred_threshold: 5.0
map_pred_threshold: 1.0
exp_pred_threshold: 1.0
collision_threshold: 0.20
kernel_size: 91
low_dense: 8
succeed_match_points: 200
big_enough_f: 0.16666666666666666
big_enough_thresh: 4
turn_angle: 15

# map
num_sem_categories: 16
map_size_cm: 3600
map_resolution: 5

# LLM and VLM
llm_model: "gpt-4o-mini-2024-07-18"
vlm_model: "gpt-4o-mini-2024-07-18"
api_key: "add_your_api_key_here"
base_url: "https://api.openai.com/v1/"